name: MySQL5.7 image build

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    name: Build on ${{ matrix.distro }} ${{ matrix.arch }}
    strategy:
      matrix:
        arch: [amd64, armv6]
        include:
          - arch: amd64
            distro: ubuntu-latest
          - arch: armv6
            distro: ubuntu20.04
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push ${{ matrix.arch }}
        uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          file: docker/build/mysql/Dockerfile
          tags: fan0o/edx-mysql-${{ matrix.arch }}:5.7
          arch: ${{ matrix.arch }}
          distro: ${{ matrix.distro }}
      -
        name: Build and push ${{ matrix.arch }}
        uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          file: docker/build/mysql/Dockerfile
          tags: fan0o/edx-mysql-${{ matrix.arch }}:5.7
          arch: ${{ matrix.arch }}
          distro: ${{ matrix.distro }}
