name: MySQL5.7 image build

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    name: Build on ${{ matrix.distro }} ${{ matrix.arch }}
    strategy:
      matrix:
        include:
          - arch: aarch64
            distro: ubuntu-latest
          - arch: armv7
            distro: ubuntu-latest
    env:      
      DOCKER_TARGET_PLATFORM: linux/arm/v7
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push amd64 image 
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: user/app:latest
          arch: ${{ matrix.arch }}
          distro: ${{ matrix.distro }}
      -
        name: Build and push arm image
        uses: docker/build-push-action@v3
        with:
          push: true
#         platforms: linux/arm/v7
          tags: edxops/mysql-arm:5.7
          arch: ${{ matrix.arch }}
          distro: ${{ matrix.distro }}
