name: MySQL5.7 image build

on:
  push:
    paths:
      - "docker/build/mysql/Dockerfile"
      - .github/workflows/edx-mysql-arm.yml
  pull_request:
    paths:
      - "docker/build/mysql/Dockerfile"
      - .github/workflows/edx-mysql-arm.yml


jobs:
  docker:
    runs-on: ubuntu-latest
    name: Build arm/amd mysql images
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: 'arm64,arm'
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push ${{ matrix.arch }}
        uses: docker/build-push-action@v3
        with:
          push: true
          context: docker/build/mysql/
          tags: fan0o/edx-mysql:5.7
          platforms: linux/amd64,linux/arm64
